using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PixARK_Tools
{
    /// <summary>
    /// Class that holds all the known cheats for PixARK. In game press "Tab", write the cheat code (or paste it) and press "Enter" to activate it.
    /// </summary>
    internal static class PixARK_Cheats
    {
        /// <summary>
        /// Code to reveal the whole world map.
        /// </summary>
        internal static readonly string Texto_Truco_Mostrar_Mapa = "cheat OpenFogOfWar";

        /// <summary>
        /// Example code to get 100 grass blocks, which can't be obtained or regenerated in game (as far as I know).
        /// </summary>
        internal static readonly string Texto_Truco_Bloque_Hierba = "cheat GiveItemNum 913 100 0 0";

        /// <summary>
        /// Array that holds the names of all the known items in PixARK, sorted by item index,
        /// and starting at "1", so add one to the array index to get the item index.
        /// Extracted from: "https://nodecraft.com/support/games/pixark/pixark-item-ids".
        /// </summary>
        internal static readonly string[] Matriz_Objetos = new string[1338]
        {
            //"None",
            "Fiber", // ID 1.
            "Dirt",
            "Rock",
            "Thatch",
            "Wood Wall",
            "Wood Ceiling",
            "Wooden Floor",
            "Wood Fence (Duplicate Of 747)",
            "Wooden Ladder",
            "Wood Door",
            "Wood Step",
            "Thatch Wall",
            "Thatch Foundation",
            "Thatch Ceiling",
            "Thatch Door",
            "Rope Ladder",
            "Wood Window",
            "Campfire",
            "Cooking Pot",
            "Leather Sleeping",
            "Storage Box",
            "Workbench",
            "Smelter",
            "Bed",
            "Stone Ceiling",
            "Stone Railing",
            "Stone Floor",
            "Stone Stair",
            "Stone Wall",
            "Clay Ceiling",
            "Clay Foundation",
            "Clay Stairs",
            "Clay Wall",
            "Wood Beast Gate",
            "Wood Behemoth Gate",
            "Mortar And Pestle",
            "Wood Chair",
            "Wood Table",
            "Wooden Sign",
            "Wood Pickaxe",
            "Bone",
            "Clay",
            "Coal",
            "Copper Ore",
            "Keratin",
            "Flint",
            "Flower",
            "Fur",
            "Gravel",
            "Leather",
            "Mushroom",
            "Sand",
            "Sandstone",
            "Chitin",
            "Volcanic Rock",
            "Water",
            "Bone Ash",
            "Charcoal",
            "Copper Ingot",
            "Fire Stone Powder",
            "Glass",
            "Salt",
            "Wood Axe",
            "Stone Axe",
            "Stone Pickaxe",
            "Copper Pickaxe",
            "Copper Axe",
            "Wood Wand",
            "Bone Wand",
            "Ankylo Saddle",
            "Argentavis Saddle",
            "Ichthyosaurus Saddle",
            "Pachy Saddle",
            "Parasaur Saddle",
            "Phiomia Saddle",
            "Pteranodon Saddle",
            "Raptor Saddle",
            "T. Rex Saddle",
            "Triceratops Saddle",
            "Drill",
            "Bow",
            "Stone Arrow",
            "Sleepy Arrow",
            "Copper Gate",
            "Copper Window",
            "Glass Gate",
            "Glass Wall",
            "Sleepy Potion",
            "Sharp Crystal (Duplicate Of 535)",
            "Magic Crystal Powder",
            "Torch",
            "Wood Stick",
            "Spear",
            "Slingshot",
            "Copper Spear",
            "Copper Sword",
            "Pistol",
            "Cloth Boots",
            "Cloth Gloves",
            "Cloth Hat",
            "Cloth Pants",
            "Cloth Shirt",
            "Leather Gloves",
            "Leather Helmet",
            "Leather Pants",
            "Leather Coat",
            "Leather Boots",
            "Chitin Boots",
            "Chitin Gauntles",
            "Chiting Helmet",
            "Chitin Leggings",
            "Chitin Breastplate",
            "Simple Bullet",
            "Wooden Spike (Duplicate 168)",
            "Wooden Spike Wall (Duplicate 166)",
            "Feeding Trough",
            "Iron Table",
            "Iron Chair",
            "Iron Signpost",
            "Magic Workbench",
            "Preserving Bin",
            "Large Storage Box",
            "Vault",
            "Fabricator (Duplicate Of 181)",
            "Crucible (Duplicate Of 193)",
            "Iron Axe",
            "Iron Pickaxe",
            "Steel Axe",
            "Steel Pickaxe",
            "Crossbow (Duplicate Of 379)",
            "Combound Bow",
            "Iron Rod",
            "Iron Spear",
            "Iron Sword",
            "Longneck Rifle (Duplicate Of 254)",
            "Shotgun (Duplicate Of 262)",
            "Apprentice Wand",
            "Test",
            "Iron Ceiling",
            "Iron Gate",
            "Iron Handrail",
            "Iron Foundation",
            "Iron Beast Gate",
            "Giant Iron Beast Gate",
            "Iron Ladder",
            "Iron Stairs",
            "Iron Wall",
            "Iron Window",
            "Marble Ceiling",
            "Marble Handrail",
            "Marble Foundation",
            "Marble Stair",
            "Marble Wall",
            "Iron",
            "Iron Ingot",
            "Steel Ingot",
            "Dark Magic Stone Essence",
            "Water Magic Stone Essence",
            "Wind Magic Stone Essence",
            "Thunder Magic Stone Essence",
            "Fire Magic Stone Essence",
            "Light Magic Stone Essence",
            "Earth Magic Stone Essence",
            "Iron Signboard",
            "Signboard On Wood Wall",
            "Wood Spike Wall (Duplicate Of 115)",
            "Iron Spike Wall",
            "Wooden Spike (Duplicate Of 114)",
            "Null",
            "Hanging Wall Torch",
            "Standing Torch",
            "Sauropod Saddle",
            "Sauropod Platform Saddle",
            "Wood Trapdoor",
            "Wood Hatch",
            "Stone Trapdoor",
            "Stone Hatch",
            "Iron Trapdoor",
            "Iron Hatch",
            "Power Generator",
            "Fabricator (Duplicate Of 124)",
            "Cross Cable",
            "Horizontal Electrical Cable",
            "Vertical Electrical Cable",
            "Junction Box",
            "Quetzal Saddle",
            "Quetzal Platform Saddle",
            "Carbonemys Saddle",
            "Beelzebufo Saddle",
            "Doedicurus Saddle",
            "Stone Beast Gate",
            "Stone Behemoth Gate",
            "Crucible (Duplicate Of 125)",
            "Alchemy Stove",
            "Dark Magic Stone",
            "Water Magic Stone",
            "Wind Magic Stone",
            "Thunder Magic Stone",
            "Fire Magic Stone",
            "Light Magic Stone",
            "Earth Magic Stone",
            "Large Wooden Platform",
            "Small Lifting Platform",
            "Medium Wooden Platform",
            "Wooden Lifting Track",
            "Stimulant (Duplicate Of 534)",
            "Styptic",
            "Healing Potion",
            "Vigor Agent",
            "Vigor Potion",
            "Small Magic Lifiting Platform",
            "Medium Magic Lifting Platform",
            "Magic Lifting Track",
            "Magic Cable Intersection",
            "Horizontal Electrical Cable",
            "Verticle Magical Energy Pipline",
            "Magic Energy Generator",
            "Magic Radiation Crystal",
            "Narcoberry",
            "Azulberry",
            "Mejoberry",
            "Tintoberry",
            "Stimberry",
            "Amaberry",
            "Cooked Meat",
            "Large Dino Feces (Duplicate Of 819)",
            "Meat",
            "Balloon Parachute",
            "Magic Mixture Night Vision Potion",
            "Magic Mixture Holy Light",
            "Steel Ceiling",
            "Steel Gate",
            "Steel Fence",
            "Steel Foundation",
            "Steel Beast Gate",
            "Giant Steel Beast Gate",
            "Steel Ladder",
            "Steel Stairs",
            "Steel Wall",
            "Steel Window",
            "Lamp Post",
            "Omnidirectional Lampost",
            "Tempered Glass Trapdoor",
            "Tempered Glass Hatch",
            "Tempered Glass Ceiling",
            "Tempered Glass Gate",
            "Tempered Glass Handrail",
            "Tempered Glass Foundation",
            "Tempered Glass Stair",
            "Tempered Glass Wall",
            "Tempered Glass Window",
            "Gold Ingot",
            "Gasoline",
            "Longneck Rifle (Duplicate Of 135)",
            "Simple Rifle Ammo",
            "Standard Assault Rifle",
            "Advanced Rifle Bullet (Duplicate Of 265)",
            "Standard Pistol",
            "Advanced Bullet",
            "Standard Sniper Rifle",
            "Advanced Sniper Bullet",
            "Shotgun (Duplicate Of 136)",
            "Shotgun Ammo",
            "Pump Action Shotgun",
            "Advanced Rifle Bullet (Duplicate Of 257)",
            "Rocket Launcher",
            "Rocket Propelled Grenade",
            "Goblin Trading Center (Duplicate Of 711)",
            "Heavy Miners Helmet",
            "Summon- Zombie (Duplciate Of 807)",
            "Light Gun",
            "Light Bullet",
            "Ballista Turret",
            "Ballista Bolt",
            "Small Metal Elevator Platform",
            "Large Metal Platform",
            "Medium Metal Platform",
            "Metal Lifting Track",
            "Copper Boots",
            "Copper Gloves",
            "Copper Helmet",
            "Copper Leggings",
            "Copper Breastplate",
            "Elemental Boots",
            "Elemental Gloves",
            "Elemental Helmet",
            "Elemental Pants",
            "Elemental Coat",
            "Iron Boots",
            "Iron Gloves",
            "Iron Helmet",
            "Iron Leggings",
            "Iron Breastplate",
            "Straight Metal Water Pipe",
            "Metal Water Tap",
            "Vertical Metal Water Pipe",
            "Horizontal Water Pipe",
            "Stone Water Tap",
            "Vertical Water Pipe",
            "Water Reservoir",
            "Metal Water Reservoir",
            "Water Bag(E)",
            "Water Bag(F)",
            "Water Jar",
            "Water Jar",
            "Water Bucket",
            "Water Bucket",
            "Icedwaterjarrefill",
            "Icedwatercanteenrefill",
            "Small Crop Plot",
            "Medium Crop Plot",
            "Chomper Seed",
            "Chomper Seed(Chinese?)",
            "Medium Dinosaur Feces (Duplicate Of 820)",
            "Inscription Book",
            "Flashlight Attachment",
            "Holographic Scope",
            "Silencer Attachment",
            "Simple Scope",
            "Emental Magic Shield",
            "Stone Water Intake Pipe",
            "Metal Water Intake Pipe",
            "Narcoberry Seed (Duplicate But Not Stacked)",
            "Narcoberry Seed (Duplicate But Not Stacked)",
            "Azulberry Seed (Duplicate But Not Stacked)",
            "Azulberry Seed (Duplicate But Not Stacked)",
            "Mejoberry Seed (Duplicate But Not Stacked)",
            "Mejoberry Seed (Duplicate But Not Stacked)",
            "Tintoberry Seed (Duplicate But Not Stacked)",
            "Tintoberry Seed (Duplicate But Not Stacked)",
            "Stimberry Seed (Duplicate But Not Stacked)",
            "Stimberry Seed (Duplicate But Not Stacked)",
            "Amarberry Seed (Duplicate But Not Stacked)",
            "Amarberry Seed (Duplicate But Not Stacked)",
            "Citronal Seed (Duplicate But Not Stacked)",
            "Citronal Seed (Duplicate But Not Stacked)",
            "Chomper Seed (No Image)",
            "Faster Chomper Seed (Test)",
            "Basic Seeds (No Image)- <Doesnt Stack",
            "Basic Seeds (No Image)- Doesnt Stack",
            "Basic Seeds (No Image)- Doesnt Stack",
            "Basic Seeds (No Image)- Doesnt Stack>",
            "Savoroot Seed (Duplicate But Not Stacked)",
            "Savoroot Seed (Duplicate But Not Stacked)",
            "Brewing Barrel",
            "Compost Bin",
            "Void",
            "Auto Turret",
            "Auto Turret (White Image)",
            "Magic Copper Axe",
            "Magic Copper Selection(Pickaxe)",
            "Magic Iron Axe",
            "Magic Iron Selection (Pickaxe)",
            "Magic Steel Axe",
            "Magic Steel Selection (Pickaxe)",
            "Magic Scroll",
            "Super Pickaxe",
            "Large Crop Plot",
            "Paintbrush",
            "Blue Dye (Duplicate Of 530)",
            "Red Dye (Duplicate Of 532)",
            "Green Dye (Duplicate Of 531)",
            "Spray Gun (Duplicate Of 506)",
            "Gryphon Saddle",
            "Elemental Golem Saddle",
            "Ghost Dragon Sadle",
            "Centaur Saddle",
            "Spring",
            "Spring Chitin Shoes",
            "Armadillo Saddle",
            "Shadow Leopard Saddle",
            "Megalodon Saddle",
            "Magic Moles Saddle",
            "Megarock Dragon Saddle",
            "Terror Bird Saddle (Duplicate Of 376)",
            "Terror Bird Saddle (Duplicate Of 375)",
            "Wooden Shield",
            "Soil",
            "Crossbow (Duplicate Of 130)",
            "Master Wand",
            "Super Test Meat (White Image)",
            "Ankylo Egg (Duplicate Of 652)",
            "Argentavis Egg (Duplicate Of 654)",
            "Compy Egg (Duplicate Of 656)",
            "Dilophosaurus Egg (Duplicate Of 658)",
            "Dodo Egg (Duplicate Of 660)",
            "Oviraptor Egg (Duplicate Of 662)",
            "Pachy Egg (Duplicate Of 664)",
            "Parasaur Egg (Duplicate Of 666)",
            "Pteranodon Egg (Duplicate Of 668)",
            "Quetzal Egg (Duplicate Of 670)",
            "Raptor Egg (Duplicate Of 672)",
            "T. Rex Egg (Duplicate Of 674)",
            "Megarock Dragons Egg (Duplicate Of 702)",
            "Sauropod Egg (Duplicate Of 676)",
            "Terror Bird Egg (Duplicate Of 680)",
            "Triceratops Egg (Duplicate Of 682)",
            "Carbonemys Egg (Duplicate Of 684)",
            "Portal",
            "Super Magic Powder",
            "Metal Sickle",
            "Mageweave Bark",
            "Magic Fiber",
            "Magic Wood",
            "Air Conditer",
            "Checkmark Flag",
            "Black Dye",
            "Orange Dye",
            "Pink Dye",
            "Purple Dye",
            "White Dye",
            "Yellow Dye",
            "Stone Shovel",
            "Iron Shovel",
            "Normal Tree Seed",
            "Mageweave Tree Seed",
            "Minitrain",
            "Train Station",
            "Left Track",
            "Right Track",
            "Downward Track",
            "Upward Track",
            "Horizontal Track",
            "Hut Diy",
            "Bunk Bed",
            "Tempered Glass Handrail (Corner)",
            "Tempered Glass Stairs (Corner)",
            "Tempered Glass Stairs (Inverted Corner)",
            "Clay Stair (Corner)",
            "Clay Stairs (Inverted Corner)",
            "Iron Handrail (Corner)",
            "Iron Stair (Corner)",
            "Iron Stair (Inverted Corner)",
            "Marble Handrail (Corner)",
            "Marble Stair (Corner)",
            "Marble Stair (Inverted Corner)",
            "Steel Fence (Corner)",
            "Steel Stair (Corner)",
            "Steel Stair (Inverted Corner)",
            "Stone Rail (Corner)",
            "Stone Stair (Corner)",
            "Stone Stair (Inverted Corner)",
            "Wood Fence (Corner) (Duplicate Of 751)",
            "Wood Step (Corner) (Duplicate Of 749)",
            "Wood Step (Inverted Corner) (Duplicate Of 750)",
            "Ceiling Lamp",
            "Fridge",
            "Electronic",
            "Bamboo Ceiling",
            "Bamboo Door",
            "Bamboo Handrail",
            "Bamboo Handrail (Corner)",
            "Bamboo Foundation",
            "Bamboo Stair",
            "Bamboo Stair (Corner)",
            "Bamboo Stair (Inverted Corner)",
            "Bamboo Wall",
            "Bamboo Window",
            "Green Vine Seed",
            "Large Muscipula Seed",
            "Nepenthes",
            "Sporeshroom Seed",
            "Ancient Lotus Seed",
            "Trapa Seed",
            "Panda Saddle",
            "Thorny Boar Saddle",
            "Double Bed",
            "Big Bed",
            "Candle Light (Duplicate Of 773)",
            "Metal Shield",
            "Metal Billboard",
            "Fertilized Ankylo Egg (Duplicate Of 653)",
            "Fertilized Argentavis Egg (Duplicate Of 655)",
            "Fertilized Compy Egg (Duplicate Of 657)",
            "Fertilized Dilo Egg (Duplicate Of 659)",
            "Fertilized Dodo Egg (Duplicate Of 661)",
            "Fertilized Oviraptor Egg (Duplicate Of 663)",
            "Fertilized Pachy Egg (Duplicate Of 665)",
            "Fertilized Parasaur Egg (Duplicate Of 667)",
            "Fertilized Pteranodon Egg (Duplicate Of 669)",
            "Green Vine Seed (Chinese?)",
            "Large Muscipula Seed (Chinese?)",
            "Nepenthes Seed (Chinese?)",
            "Sporeshroom Seed (Chinese?)",
            "Ancient Lotus Seed (Chinese?)",
            "Trapa Seed (Chinese?)",
            "Steel Sickle (Duplicate Of 505)",
            "Wheat",
            "Bamboo Shoot",
            "Truffle",
            "Longrass",
            "Savoroot",
            "Rockarrot",
            "Fruit Juice",
            "Bread",
            "Bamboo Shoot Soup",
            "Truffle Soup",
            "Baked Longrass",
            "Roast Savoroot",
            "Rockarrot Soup",
            "Sour Fruit Juice",
            "Cake",
            "Concentrated Fruit Juice",
            "Chainsaw",
            "Steel Sickle (Duplicate Of 487)",
            "Spray Gun (Duplicate Of 363)",
            "Smoke Grenade",
            "Poison Grenade",
            "Grenade",
            "Electric Prod",
            "Copper Kettle(E)",
            "Copper Kettle(F)",
            "Truffle Seed (Doesnt Stack)",
            "Truffle Seed (Doesnt Stack)",
            "Wheat Seed (Doesnt Stack)",
            "Wheat Seed (Doesnt Stack)",
            "Longrass Seed (Doesnt Stack)",
            "Longrass (Doesnt Stack)",
            "Rockarrot Seed (Doesnt Stack)",
            "Rockarrot Seed (Doesnt Stack)",
            "Mine",
            "Homing Underwater Mine",
            "Fishing Rod",
            "Sulfur",
            "Gunpowder",
            "Sleepy Dart",
            "Chitin(Ground)",
            "Polymer",
            "Industrial Cauldon",
            "Blue Dye (Duplicate Of 360)",
            "Green Dye (Duplicate Of 361)",
            "Red Dye (Duplicate Of 362)",
            "Null",
            "Stimulant (Duplicate Of 206)",
            "Sharp Crystal (Duplicate Of 89)",
            "Quartz",
            "Magic Sleepy Arrow",
            "Raw Thigh Meat",
            "Cooked Prime Meat",
            "Primary Magic Core",
            "Ice (Duplicate Of 552)",
            "Carrion",
            "Volcanic Rock Cube",
            "Cwresourcescube55",
            "Dark Ruins Brick(Solid)",
            "Dark Ruins Brick(Decorative)",
            "Dungeon Ruins Brick",
            "Dungeon Ruins Brick(Smooth)",
            "Pyramid Ruin Wall",
            "Pyramid Ruin Wall(Smooth)",
            "Mysteriousbox",
            "Ice (Duplicate Of 541)",
            "Marble",
            "Petroleum Bumppump",
            "Petroleum Pipe",
            "Curved Pteroleum Pipe",
            "Petroleum Tower",
            "Petroleum Barrel",
            "Petroleum",
            "Summon-Skeleton (Duplicate Of 806)",
            "Simple Glider",
            "Magic Wood Ceiling",
            "Magic Wood Trapdoor",
            "Magic Wood Door",
            "Magic Wood Railing",
            "Magic Wood Railing(Corner)",
            "Magic Wood Foundation",
            "Magic Wood Roof (Duplicate Of 569 570)",
            "Magic Wood Roof (Duplicate Of 568 570)",
            "Magic Wood Roof Duplicate Of 568 569)",
            "Magic Wood Stair (Duplicate Of 572 573)",
            "Magic Wood Stair (Duplicate Of 571 573)",
            "Magic Wood Stair (Duplicate Of 571 572)",
            "Magic Wood Wall",
            "Magic Wood Window",
            "Elemental Spirit Core",
            "Fire Elemental Core",
            "Goblin Trade Center Drawing",
            "Ice Elemental Core",
            "Megalodon Skin",
            "Megalodod Skull",
            "Plague Heart",
            "Pteranodon Wing",
            "Big-Ear Rabbit Fur",
            "T. Rex Skull",
            "Skeleton",
            "Terror Bird Beak",
            "Triceratops Skull",
            "Zombie Heart",
            "Terror Bird Beak Helmet Skin",
            "Megalodon Helmet Skin",
            "Rabbit Ear Hat Skin",
            "T. Rex Bone Helmet Skin",
            "Triceratops Bone Helmet Skin",
            "Scuba Flippers",
            "Diving Gloves",
            "Scuba Mask",
            "Scuba Leggings",
            "Scuba(Tank)",
            "Gas Mask",
            "Bug Repellant",
            "Crit-Proof Shield",
            "Water Cube",
            "Lava Cube",
            "Oil",
            "Bamboo Lamp",
            "Bamboo Chair",
            "Candle (Duplicate Of 772)",
            "Candle Stick",
            "Wall Candlestick (Duplicate Of 775)",
            "Ceiling Brazier",
            "Wall Lamp (Duplicate Of 776)",
            "Fur Coat",
            "Fur Pants",
            "Fur Helmet",
            "Fur Glove",
            "Fur Boots",
            "Steel Shirt",
            "Steel Pants",
            "Steel Helmet",
            "Steel Gloves",
            "Steel Boots",
            "Fungus Beast Saddle",
            "Fairy Dragon Saddle",
            "Kibble (Ankylo Egg)",
            "Kibble (Argentavis Egg)",
            "Kibble (Compy Egg)",
            "Kibble (Dilophosaurus Egg)",
            "Kibble (Dodo Egg)",
            "Kibble (Oviraptor Egg)",
            "Kibble (Pachy Egg)",
            "Kibble (Parasaur Egg)",
            "Kibble (Pteranodon Egg)",
            "Kibble (Quetzal Egg)",
            "Kibble (Raptor Egg)",
            "Kibble (Rex Egg)",
            "Kibble (Sauropod Egg)",
            "Kibble (Emperor Scorpion Egg)",
            "Kibble (Terror Bird Egg)",
            "Kibble (Triceratops Egg)",
            "Kibble (Carbonemys Egg)",
            "Kibble (Armadillo Egg)",
            "Kibble (Fairy Dragon Egg)",
            "Kibble (Fire Spider Egg)",
            "Kibble (Fungus Beast Egg)",
            "Kibble (Gem Spider Egg)",
            "Kibble (Gryphon Egg)",
            "Kibble (Icicle Dragon Egg)",
            "Kibble (Pegasus Egg)",
            "Kibble (Megarock Dragon Egg)",
            "Kibble (Ghost Dragon Egg)",
            "Ankylo Egg (Duplicate Of 382)",
            "Fertilized Ankylo Egg (Duplicate Of 472)",
            "Argentavis Egg (Duplicate Of 383)",
            "Fertilized Argentavis Egg (Duplicate Of 473)",
            "Compy Egg (Duplicate Of 384)",
            "Fertilized Compy Egg (Duplicate Of 474)",
            "Dilophosaurus Egg (Duplicate Of 385)",
            "Fertilized Dilophosaurus Egg (Duplicate Of 475)",
            "Dodo Egg (Duplicate Of 386)",
            "Fertilized Dodo Egg (Duplicate Of 476)",
            "Oviraptor Egg (Duplicate Of 387)",
            "Fertilized Oviraptor Egg (Duplicate Of 477)",
            "Pachy Egg (Duplicate Of 388)",
            "Fertilized Pachy Egg (Duplicate Of 478)",
            "Parasaur Egg (Duplicate Of 389)",
            "Fertilized Parasaur Egg (Duplicate Of 479)",
            "Pteranodon Egg (Duplicate Of 390)",
            "Fertilized Pteranodon Egg (Duplicate Of 480)",
            "Quetzal Egg (Duplicate Of 391)",
            "Fertilized Quetzal Egg",
            "Raptor Egg (Duplicate Of 392)",
            "Fertilized Raptor Egg",
            "T. Rex Egg (Duplicate Of 393)",
            "Fertilized T. Rex Egg",
            "Sauropod Egg (Duplicate Of 395)",
            "Fertilized Sauropod Egg",
            "Emperor Scorpion Egg",
            "Fertilized Emperor Scorpion Egg",
            "Terror Bird Egg (Duplicate Of 396)",
            "Fertilized Terror Bird Egg",
            "Triceratops Egg (Duplicate Of 397)",
            "Fertilized Triceratops Egg",
            "Carbonemys(Egg) (Duplicate Of 398)",
            "Fertilized Carbonemys Egg",
            "Armadillo Egg",
            "Fertilized Armordillo Egg",
            "Fairy Dragon Egg",
            "Fertilized Fairy Dragon",
            "Fire Spider Egg",
            "Fertilized Fire Spider Egg",
            "Fungus Beast Egg",
            "Fertilized Fungus Beast Egg",
            "Gem Spider Egg",
            "Fertilized Gem Spider Egg",
            "Gryphon Egg",
            "Fertilized Gryphon Egg",
            "Icicle Dragon Egg",
            "Fertilized Icicle Dragon Egg",
            "Pegasus Egg",
            "Fertilized Pegasus Egg",
            "Megarock Dragon Egg (Duplicate Of 394)",
            "Fertilized Megarock Dragon Egg",
            "Ghost Dragon Egg",
            "Fertilized Ghost Dragon Egg",
            "Citronal",
            "Magic Berry Seed",
            "Fast Magic Berry Seed(Test)",
            "Tree Seed (Chinese?)",
            "Gold",
            "Goblin Trading Center (Duplicate Of 268)",
            "Chest",
            "Frigid Tree Seed",
            "Frigid Tree Seed (Chinese?)",
            "Swamp Tree Seed",
            "Swamp Tree Seed (Chinese?)",
            "Plateau Tree Seed",
            "Plateau Tree Seed (Chinese?)",
            "Tropical Tree Seed",
            "Tropical Tree Seed (Chinese?)",
            "Temperate Tree Seed",
            "Temperate Tree Seed (Chinese?)",
            "Human Feces (Duplicate Of 822)",
            "Mageweave Tree Rapid Version",
            "Werewolf Potion",
            "Bamboo(Packet)",
            "Black Vine(Packet)",
            "Blue Magic Stone(Packet)",
            "Copper Ore(Packet)",
            "Green Magic Stone(Packet)",
            "Iron Ore(Packet)",
            "Mageweave Bark(Packet)",
            "Spinel Ore(Packet)",
            "Magic Fiber(Packet)",
            "Magic Wood(Packet)",
            "Purple Magic Crystal(Packet)",
            "Quartz(Packet)",
            "Red Magic Crystal(Packet)",
            "Silver(Packet)",
            "White Magic Crystal(Packet)",
            "Yellow Magic Crystal(Packet)",
            "Werewolf Blood",
            "Metal Arrow",
            "Wooden Raft",
            "Thatch Roof",
            "Wood Trapdoor",
            "Wood Fence (Duplicate Of 8)",
            "Wood Roof",
            "Wood Step(Corner) (Duplicate Of 444)",
            "Wood Step(Inverted Corner) (Duplicate Of 445)",
            "Wood Fence (Corner) (Duplicate Of 443)",
            "Thatch Carpet",
            "Wooden Bench",
            "Magician Boots",
            "Magician Gloves",
            "Magician Helmet",
            "Magician Pants",
            "Magician Coat",
            "Dark Blue Dye",
            "Dark Green Dye",
            "Dark Orange Dye",
            "Dark Pink Dye",
            "Light Yellow Dye",
            "Sea Blue Dye",
            "Sky Blue Dye",
            "Barrel Of Oil",
            "Gasoline",
            "Thunder Totem",
            "Turtle Shell Shield",
            "Ice Shield",
            "Rebound Damage Shield",
            "Candle (Duplicate Of 608)",
            "Candle Light (Duplicate Of 469)",
            "Candlestick",
            "Wall Candlestick (Duplicate Of 610)",
            "Wall Lamp (Duplicate Of 612)",
            "Specimen Impant",
            "Treetest",
            "Treetest",
            "Doedicurus Hammer",
            "Magic Ballista Bolt",
            "Centaur Spear 782",
            "Mole Pick",
            "Ankylo Shell",
            "Armadillo Shell",
            "Dilophosaurus Venom",
            "Doedicurus Tail",
            "Icebear Shell",
            "Icicle Dragon Bone",
            "Raptor Claw",
            "Turtle Shell",
            "Blind Arrow",
            "Ice Arrow",
            "Lava Boots",
            "Lava Gloves",
            "Lava Helmet",
            "Lava Pants",
            "Lava Armor",
            "Sarco Egg",
            "Fertilized Sarco Egg",
            "Kibble (Sarco Egg)",
            "Sarco Saddle",
            "Decoration Hut",
            "Tailor'S Workbench",
            "Summon-Plague Zombie",
            "Summon - Skeleton (Duplicate Of 560)",
            "Summon - Zombie (Duplicate Of 270)",
            "Boulder",
            "Cassiopeia",
            "Dinosaur",
            "Paradise",
            "Raptor Claw(Weapon)",
            "Mole Claws",
            "Shining Wand",
            "Pegasus Horn",
            "Fertilizer",
            "Dye Workbench",
            "Feed Pot",
            "Large Dino Feces (Duplicate Of 226)",
            "Medium Dinosaur Feces (Duplicate Of 314)",
            "Small Dino Feces",
            "Human Feces (Duplicate Of 723",
            "Angler Saddle",
            "Glass Bottle",
            "Manta Saddle",
            "Manta Platform Saddle",
            "Spring Steel Shoes",
            "Iron Spring Boots",
            "Super Drill",
            "Cannon",
            "Cannon Ball",
            "Blueprint",
            "Ore Detector (Duplciate Of 834)",
            "Ore Detector (Duplciate Of 833)",
            "Mediterranean Bridge Blueprint",
            "Mediterranean Ceiling Blueprint",
            "Mediterranean Gate Blueprint",
            "Mediterranean Fence Blueprint",
            "Mediterranean Foundation Blueprint",
            "Mediterranean Step Blueprint",
            "Mediterranean Roof Blueprint",
            "Mediterranean Wall Blueprint",
            "Mediterranean Window Blueprint",
            "Mediterranean Bridge",
            "Mediterranean Ceiling",
            "Mediterranean Fence",
            "Mediterranean Foundation",
            "Mediterranean Gate",
            "Mediterranean Stair",
            "Mediterranean Roof",
            "Mediterranean Wall",
            "Mediterranean Window",
            "Flame Feather Costume",
            "Grappling Hook",
            "Candle Helmet",
            "Argentavis Feather",
            "Dino Tracker Ammo",
            "Dino Tracker",
            "Treant Defense Tower",
            "Parachute",
            "Bait",
            "Cactus",
            "Cactus Juice",
            "Cactus Seed",
            "Aeolian Grass",
            "Black Vine",
            "Blue Ray Thorn",
            "Chilling Grass",
            "Flame Flower",
            "Gold Leaf",
            "Ice Lotus",
            "Thick Earth Crystal",
            "Ice Shard",
            "Small Ice Lotus",
            "Poisonous Mushroom",
            "Light Mushroom",
            "Small Light Mushroom",
            "Guide Post",
            "Firefly Pillar Lamp",
            "Firefly Wall Lamp",
            "Firefly Ceiling Lamp",
            "Relic Ruins Brick(Decorative)",
            "Relic Ruins Brick",
            "Magic Dirt",
            "Bamboo",
            "Rocket Backpack",
            "Small Ice Bamboo Flower",
            "Small Ice Lotus",
            "Small Ice Lotus",
            "Small Ice Lotus",
            "Small Rattan",
            "Null",
            "Small Cactus",
            "Monster Box",
            "Soil",
            "Wind Driven Generator",
            "Ice Cellar",
            "Scuba Potion",
            "Power Potion",
            "Swiftness Potion",
            "Load Potion",
            "Craftsman Potion",
            "Triceratops Skull(Placeable)",
            "Triceratops Torso Skeleton(Placeable)",
            "Rex Skull (Placeable)",
            "Rex Trunk (Placeable)",
            "Gryphon Skull (Placeable)",
            "Gryphon Trunk (Placeable)",
            "Ice Spear",
            "Procoptodon Saddle",
            "Snow",
            "Windburnisher",
            "Grass Cube",
            "Catapult Turret",
            "Gigantopithicus Drawbridge",
            "Clay Roof",
            "Phiomia Hut",
            "Magic Academy Bridge",
            "Magic Academy Ceiling",
            "Magic Academy Gate",
            "Magic Academy Femce",
            "Magic Academy Floor",
            "Magic Academy Stairs",
            "Magic Academy Roof",
            "Magic Academy Stone Wall",
            "Magic Academy Stone Window",
            "Magic Academy Bridge Bp",
            "Magic Academy Ceiling Bp",
            "Magic Academy Gate Bp",
            "Magic Academy Fence Bp",
            "Magic Academy Floor Bp",
            "Magic Academy Stairs Bp",
            "Magic Academy Roof Bp",
            "Magic Academy Stone Wall Bp",
            "Magic Academy Stone Window Bp",
            "Stegosaurus Saddle",
            "Carnotaurus Saddle",
            "Amethyst Cube",
            "Bedrock Cube",
            "Black Agate Cube",
            "Brenstone Cube",
            "Clay Cube",
            "Coal Cube",
            "Copper Cube",
            "Gravel Cube",
            "Emerald Cube",
            "Gold Cube",
            "Iron Ore Cube",
            "Magic Grass Cube",
            "Quartz Cube",
            "Ruby Cube",
            "Topaz Cube",
            "Spinel Cube",
            "White Jade Cube",
            "Yellow Amber Cube",
            "Silver Ore Cube",
            "Pressure Detector",
            "Train Building Platform",
            "Y Track",
            "Press Detection Track",
            "Cable Switch",
            "Brazier",
            "Monster Box(Spawner)",
            "Chest",
            "Null",
            "Snow Ball",
            "Fruit Dispaly Stand",
            "Magic Berry",
            "Paracer Saddle",
            "Paracer Platform Saddle",
            "Gun Display Stand",
            "Spear Display Stand",
            "Cloth Golves(Hideforcamera)",
            "Fertilizer(Bag)",
            "Weapon Rack",
            "Sword Display Stand",
            "Bamboo Roof",
            "Glass Fence",
            "Glass Roof",
            "Marble Door",
            "Marble Window",
            "Clay Window",
            "Magic Wood Ladder",
            "Magic Wood Beast Gate",
            "Magic Wood Behemoth Gate",
            "Magic Wood Hatch",
            "Stone Stairs(Ladder)",
            "Stone Wall",
            "Costume Display Rack",
            "Glass Window",
            "Magic Academy Bed",
            "Magic Academy Chair",
            "Magic Academy Storage Box",
            "Magic Academy Table",
            "Clay Door",
            "Moonlight Dust",
            "Gray Berry",
            "Green Berry",
            "Moonlight Berry",
            "Orange Berry",
            "Pink Berry",
            "Gray Dye",
            "Theft",
            "Executive Style Bridge",
            "Executive Style Ceiling",
            "Executive Style Door",
            "Executive Style Fence",
            "Executive Style Floor",
            "Executive Style Roof",
            "Executive Style Step",
            "Executive Style Wall",
            "Executive Style Window",
            "Executive Style Bridge Bp",
            "Executive Style Ceiling Bp",
            "Executive Style Door Bp",
            "Executive Style Fence Bp",
            "Executive Style Floor Bp",
            "Executive Style Roof Bp",
            "Executive Style Sign Bp",
            "Executive Style Step Bp",
            "Executive Style Wall Bp",
            "Executive Style Window Bp",
            "Magic Academy Bed Bp",
            "Magic Academy Chair Bp",
            "Magic Academy Storage Box Bp",
            "Magic Academy Table Bp",
            "Mediterranean Chair Bp",
            "Mediterranean Bed Bp",
            "Mediterranean Storage Box Bp",
            "Mediterranean Table Bp",
            "Western Wood Bed Bp",
            "Western Wood Bridge Bp",
            "Western Ceiling Bp",
            "Western Wood Chair Bp",
            "Western Wood Door Bp",
            "Western Wood Fence Bp",
            "Western Wood Floor Bp",
            "Western Wood Stair Bp",
            "Western Storage Box Bp",
            "Western Wood Table Bp",
            "Western Roof Bp",
            "Western Wood Wall Bp",
            "Western Wood Window Bp",
            "Copper Bone Sword",
            "Iron Bone Sword",
            "Steel Sword",
            "Steel Bone Sword",
            "Magic Sword(Test)",
            "Copper Bone Boots",
            "Copper Bone Gloves",
            "Copper Bone Helmet",
            "Copper Bone Pants",
            "Copper Bone Shirt",
            "Iron Bone Boots",
            "Iron Bone Gloves",
            "Iron Bone Helmet",
            "Iron Bone Pants",
            "Iron Bone Shirt",
            "Steel Bone Boots",
            "Steel Bone Gloves",
            "Steel Bone Helmet",
            "Steel Bone Pants",
            "Steel Bone Short",
            "Cryolite Ceiling",
            "Cryolite Door",
            "Cryolite Fence",
            "Cryolite Floor",
            "Cryolite Ladder",
            "Cryolite Roof",
            "Cryolite Step",
            "Cryolite Wall",
            "Cryolite Window",
            "Dark Wood Ceiling",
            "Dark Wood Door",
            "Dark Wood Fence",
            "Dark Wood Floor",
            "Dark Wood Ladder",
            "Dark Wood Roof",
            "Dark Wood Step",
            "Dark Wood Wall",
            "Dark Wood Window",
            "Flash Rock Ceiling",
            "Flash Rock Door",
            "Flash Rock Fence",
            "Flash Rock Floor",
            "Flash Rock Ladder",
            "Flash Rock Roof",
            "Flash Rock Step",
            "Flash Rock Wall",
            "Flash Rock Window",
            "Volcanic Rock Ceiling",
            "Volcanic Rock Gate",
            "Volcanic Rock Fence",
            "Volcanic Rock Floor",
            "Volcanic Rock Ladder",
            "Volcanic Rock Roof",
            "Volcanic Rock Step",
            "Volcanic Rock Wall",
            "Volcanic Rock Window",
            "Sea Crystal Ceiling",
            "Sea Crystal Door",
            "Sea Crystal Fence",
            "Sea Crystal Floor",
            "Sea Crystal Ladder",
            "Sea Crystal Roof",
            "Sea Crystal Stair",
            "Sea Crystal Wall",
            "Sea Crystal Window",
            "Monsterbox_Thanatos(Spawner?)",
            "Algae",
            "Coral",
            "Coral Rock",
            "Cursed Soil",
            "Dark Wood",
            "Flashrock",
            "Ice Crystal",
            "Scorched Earth",
            "Sea Crystal",
            "Soul Sand",
            "Starfish",
            "Primal Bone Pieces",
            "Hard Bone Pieces",
            "Splendid Bone Pieces",
            "Magic Boots (Test)",
            "Magic Handguard(Test)",
            "Magic Helmet(Test)",
            "Magic Leggings(Test)",
            "Magic Armor(Test)",
            "Darl Ruins Brick",
            "Dungeon Ruins Brick",
            "Pyramid Ruin Brick",
            "Relic Ruins Brick",
            "Ocean Ruins Brick",
            "Ocean Rins Brick(W/Green)",
            "Ocean Ruins Brick(Glow)",
            "Ice Ruins Brick",
            "Ice Ruins Brick(Square Cut)",
            "Ice Ruins Brick(Smooth)",
            "Moss Ruins Cube(Brick)",
            "Moss Ruins Cube(Square Cut)",
            "Moss Ruins Cube(W/ Ruins)",
            "Bookshelf",
            "Overgrown Soil Block",
            "Flash Grass Block",
            "Flash Soil Block",
            "Cursed Grass Block",
            "Cursed Soil Block",
            "Soul Sand",
            "Corralrock",
            "Sea Crystal",
            "Flash Rock",
            "Icespar_Desc",
            "Soul Liquid",
            "Dirt Brown",
            "Dirt Grey",
            "Dirt_Grey Fade",
            "Dirt_Lightgreen",
            "Dirt_Mageta",
            "Dirt_Orange",
            "Dirt_Purple",
            "Dort_Yellow",
            "Simple Mask",
            "Mist Tree Seed",
            "Gray Seed",
            "Green Berry Seed",
            "Orange Berry Seed",
            "Pink Seed",
            "Magic Flash Berry Seed",
            "Fire Switch",
            "Wooden Floor",
            "Wood Wall",
            "Wood Ceiling",
            "Stone Floor",
            "Stone Wall",
            "Stone Ceiling",
            "Flame Dragon Saddle",
            "Ice Ruins Brick(Flame)",
            "Firearm Worktable",
            "Felhunter Saddle",
            "Broken Ruins Brick",
            "Broken Ruins Brick(Stones)",
            "Broken Ruins Brick(Wood)",
            "Relicmonsteranglerfish(Spawner?)",
            "Relicmonsterbat(Spawner?)",
            "Relicmonsterdilophosaurus(Spawner?)",
            "Relicmonstericebear(Spawner?)",
            "Relicmonstericicledinosaur(Spawner?)",
            "Relicmonsterpiranha(Spawner?)",
            "Pistol",
            "Monsterbox Behemoth",
            "Longneck Rifle",
            "Pistol Bullet",
            "Fire Bullet",
            "Ice Bullet",
            "Poison Bullet",
            "Flashlight Attachment",
            "Simple Scope",
            "Silencer Attachment",
            "Railprotectfilm",
            "Trainyard",
            "Shotgun",
            "Hippocampus Saddle",
            "Standard Pistol",
            "Flower Pot",
            "Pump-Action Shotgun",
            "Doom Ruins Brick(Brick)",
            "Doom Ruins Brick(Spiked)",
            "Doom Ruins Wall",
            "Metal Ruins Cube(Caution)",
            "Metail Ruins Cube(Iron)",
            "Metal Ruins Cube(Reflective)",
            "Standard Assault Rifle",
            "Rocket Launcher",
            "Standard Sniper Rifle",
            "Chest(Blue/Silver Loot)",
            "Chest(Turqoise/Spike Loot)",
            "Chest(Green/Ornate Loot)",
            "Chest(Blue/Silver Empty)",
            "Chest(Turqoise/Spike Empty)",
            "Chest(Green/Ornate Empty)",
            "Chest(Wood Loot)",
            "Chest(Wood/Iron Loot)",
            "Chest(Blue/Silver Loot+)",
            "Chest(Wood Loot+)",
            "Chest(Wood/Iron Loot+)",
            "Chest(Blue/Silver Gear)",
            "Chest(Wood/Iron Gear)",
            "Chest(Blue/Silver Resources+)",
            "Chest(Turqoise/Spike Resources)",
            "Chest(Wood/Iron Ammo)",
            "Chest(Blue/Silver Resources)",
            "Chest(Turqoise/Spike Resources+)",
            "Chest(Wood Tools)",
            "Chest(Wood/Iron Gear)",
            "Chest(Wood Arrows)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Iron Ore Cube(Null)",
            "Bedrock Cube (Oil?)",
            "Advanced Rifle Bullet",
            "Sniper Bullet",
            "Fire Type Rocket Launcher Grenade",
            "Ice Type Rocket Launcher Grenade",
            "Rocket Propelled Grenade",
            "Poison Type Rocket Launcher Grenade",
            "Shotgun Ammo",
            "Aeolian Grass Seed",
            "Black Vine Seed",
            "Blue Ray Thorn Seed",
            "Chilling Grass Seed",
            "Flame Flower Seed",
            "Gold Leaf Seed",
            "Ice Lotus Seed",
            "Thick Earth Crystal Seed",
            "Fire-Type Shotgun Ammo",
            "Ice-Type Shotgun Ammo",
            "Poison-Type Shotgun Ammo",
            "Cryolite Bed",
            "Cryolite Chair",
            "Cryolite Storage Box",
            "Cryolite Table",
            "Dark Wood Bed",
            "Dark Wood Chair",
            "Dark Wood Storage Box",
            "Dark Wood Table",
            "Volcanic Rock Bed",
            "Volcanic Rock Chair",
            "Volcanic Rock Storage Box",
            "Volcanic Rock Table",
            "Flash Rock Bed",
            "Flash Rock Chair",
            "Flash Rock Storage Box",
            "Flash Rock Table",
            "Sea Crystal Bed",
            "Sea Crystal Chair",
            "Sea Crystal Storage Box",
            "Sea Crystal Table",
            "Dvlsmrcy",
            "Ecomodsgames",
            "022518",
            "Candle Bp",
            "Candlestick Bp",
            "Wall Candlestick Bp",
            "Bamboo Ceiling Bp",
            "Bamboo Chair Bp",
            "Bamboo Door Bp",
            "Bamboo Fence Bp",
            "Bamboo Foundation Bp",
            "Bamboo Lamp Blueprint",
            "Bamboo Roof Bp",
            "Bamboo Divider Bp",
            "Bamboo Step Bp",
            "Bamboo Table Bp",
            "Bamboo Wall Bp",
            "Bamboo Window Bp",
            "Industrial Smelter",
            "Tempered Glass",
            "Stone Door",
            "Western Wood Brindge",
            "Western Ceiling",
            "Western Wood Door",
            "Westerm Wood Fence",
            "Western Wood Floor",
            "Westerm Wood",
            "Western Wood Stair",
            "Western Roof",
            "Westerm Wood Wall",
            "Westerm Wood Window",
            "Executive Style Sign",
            "Lost",
            "Copper Ore",
            "Marbles",
            "Compiled",
            "By",
            "Pixblock Container",
            "Ah",
            "With",
            "Empty Pixblock",
            "Help", // ID 1.338.
        };
    }
}
